### ISSUE TITLE
Sensor names...

### ISSUE THREAD

**Issue by Snille** [azureflipper/f750hacard#1]
Hi! Thank you for this card! :)
Do you know if there is a "Translation-table" for the numbers of the sensors? All of mine have "names" instead of the numbers... 
Like tihs:
![image](https://user-images.githubusercontent.com/1011699/214959879-37b72b17-4202-42e7-8064-3383246b8db4.png)
And in your card, all the sensors are "numbers". :)

**Comment by Snille** [comment]
Hi again, I think I figured it out...
Here are all my sensors with the "names"... If someone else has the same problem.
Let me know if I put the wrong sensor in some place. 
If all looks good you can close the issue. :)
```
type: picture-elements
elements:
  - entity: sensor.nibe_storstugan_exhaust_air
    style:
      left: 68.5%
      top: 4%
      color: orange
    type: state-label
  - entity: sensor.nibe_storstugan_extract_air
    style:
      left: 49%
      top: 4%
      color: lightblue
    type: state-label
  - entity: sensor.nibe_storstugan_air_velocity_sensor_value
    style:
      left: 49%
      top: 15%
      color: black
    type: state-label
  - entity: sensor.nibe_storstugan_air_reference_velocity_sensor
    style:
      left: 68.5%
      top: 15%
      color: black
    type: state-label
  - entity: sensor.nibe_storstugan_current_compressor_frequency
    prefix: ''
    style:
      left: 15%
      top: 26.1%
      color: black
    type: state-label
  - entity: sensor.nibe_storstugan_allowed_compressor_frequency
    prefix: ''
    style:
      left: 15%
      top: 31.5%
      color: black
    type: state-label
  - entity: sensor.nibe_storstugan_hot_water_top
    style:
      left: 58.5%
      top: 45%
      color: orange
    type: state-label
  - entity: water_heater.nibe_storstugan_hot_water
    style:
      left: 58.5%
      top: 56%
      color: black
    type: state-label
  - entity: sensor.nibe_storstugan_hot_water_charging
    style:
      left: 58.5%
      top: 74%
      color: lightblue
    type: state-label
  - entity: sensor.nibe_storstugan_pump_speed_heating_medium
    style:
      left: '-1.5%'
      top: 56.8%
      color: black
      font-size: 0.8vw
      transform: rotate(-90deg)
    type: state-label
  - entity: sensor.nibe_storstugan_electrical_addition_power
    style:
      left: 13.8%
      top: 56.6%
      color: black
      font-size: 0.85vw
      transform: rotate(-90deg)
    type: state-label
  - entity: sensor.nibe_storstugan_supply_temp
    style:
      left: 32%
      top: 93%
      color: black
    type: state-label
  - entity: sensor.nibe_storstugan_return_temp
    style:
      left: 86.5%
      top: 93%
      color: black
    type: state-label
  - entity: sensor.nibe_storstugan_degree_minutes
    style:
      left: 34.3%
      top: 28.7%
      color: black
      font-size: 0.60vw
    type: state-label
    suffix: null
  - type: conditional
    conditions:
      - entity: sensor.nibe_heating_priority
        state: water
    elements:
      - type: icon
        icon: mdi:arrow-right-drop-circle-outline
        icon-size: null
        style:
          top: 46.96%
          left: 30.4%
          color: darkorange
  - type: conditional
    conditions:
      - entity: sensor.nibe_heating_priority
        state: heating
    elements:
      - type: icon
        icon: mdi:arrow-down-drop-circle-outline
        icon-size: null
        style:
          top: 46.96%
          left: 30.4%
          color: black
  - type: conditional
    conditions:
      - entity: sensor.nibe_heating_priority
        state: heating
    elements:
      - type: state-label
        entity: sensor.nibe_storstugan_heat_delta_t_calculated_value
        prefix: 'dT calc: '
        style:
          left: 52%
          top: 97.5%
          color: black
  - type: conditional
    conditions:
      - entity: sensor.nibe_heating_priority
        state: heating
    elements:
      - type: state-label
        entity: sensor.nibe_storstugan_heat_delta_t_is_bt12_bt63_bt3
        prefix: 'dT is: '
        style:
          left: 68%
          top: 97.5%
          color: black
image: F750-hass-drawing.png
```
